name: CI
on:
  push:
    branches:
    - main
    tags-ignore:
    - "*.*.*"
  pull_request:
    branches:
    - main
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go: ["1.18"]
        os: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
    - uses: actions/checkout@v3
    - name: go test
      run: "go test -v -race -coverprofile=coverage.txt -covermode=atomic ./..."
    - uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.txt
